services:
  starprobe:
    build:
      target: production
    ports:
      - "${STARPROBE_BIND_IP:-0.0.0.0}:${STARPROBE_BIND_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - CONTAINER_ENV=production
      # Mock settings - these override .env file when passed from environment
      - STARPROBE_USE_MOCK_NEXUS=${STARPROBE_USE_MOCK_NEXUS}
      - STARPROBE_USE_MOCK_SEARCH=${STARPROBE_USE_MOCK_SEARCH}
      - STARPROBE_USE_MOCK_SCRAPING=${STARPROBE_USE_MOCK_SCRAPING}
