"""Pydantic models for SDK."""

from typing import Any

from pydantic import BaseModel, Field


class ResearchResponse(BaseModel):
    """Response model for research endpoint."""

    success: bool = Field(..., description="Whether research completed successfully")
    article: str | None = Field(
        None, description="Fully rendered Markdown article generated by the service"
    )
    metadata: dict[str, Any] | None = Field(
        default=None,
        description="Additional metadata such as sources, counts, or diagnostics",
    )
    error_message: str | None = Field(None, description="Error details if failed")
    diagnostics: list[str] = Field(
        default_factory=list, description="Diagnostics collected during research"
    )
    processing_time: float = Field(
        ..., description="Time taken to process the request in seconds"
    )
